name: Jerboa Dance
markdown: kramdown

google_analytics: UA-1310792-1

collections:
  company:
    output: true
  performances:
    output: true

defaults:
  - scope:
      path: ""
      type: company
    values:
      layout: bio
      role: Dancer
      status: inactive
  - scope:
      path: ""
      type: performances
    values:
      layout: performance
      upcoming: false